version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PenisTooBig
      MYSQL_DATABASE: Users
      MYSQL_USER: BobTheBuilder
      MYSQL_PASSWORD: PenisTooSmall
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql # Legger inn testdata
    networks:
      - app_network
    ports:
      - "3306:3306"

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
